sudo: false

language: node_js
node_js:
  - "node"

addons:
  postgresql: "9.4"

before_script:
  - "psql -c 'create database transwrap_test;' -U postgres"

script: "npm run test-travis"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
