sudo: false

language: node_js
node_js:
  - "node"

addons:
  postgresql: "9.4"
  mysql: "5.7"

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres

before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS transwrap_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS transwrap_test;'; fi"


script: "npm run test-travis"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
